[package]
name = "numbers"
version = "0.1.0"
authors = ["Siddharth Borderwala <siddharthborderwala@gmail.com>"]
edition = "2018"

[[bin]]
name = "pi"
path = "src/pi.rs"

[[bin]]
name = "parse"
path = "src/parse.rs"

[dependencies]
